logging:
  level:
    root: INFO
    org:
      springframework:
        security:
          oauth2: INFO
        ws:
          server:
            MessageTracing:
              received: TRACE
              sent: TRACE
        jdbc:
          core: TRACE
      thymeleaf: INFO
  config: classpath:log4j-spring.xml
server:
  port: 8081
  servlet:
    context-path: /lambda-auth
    encoding:
      charset: UTF-8
      enabled: true
  error:
    whitelabel:
      enabled: false
    path: /error
spring:
  application:
    name: lambda-auth-service
  redis:
    url: ${REDIS_TLS_URL:}
  session:
    store-type: redis
    redis:
      namespace: lambda:auth:session
      flush-mode: on_save
      cleanup-cron: "0 * * * * *"
    timeout: 1h
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 100000
      maxLifetime: 900000
      maximum-pool-size: 20
      minimum-idle: 10
    initialization-mode: never
    url: jdbc:${CLEARDB_DATABASE_URL:}
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: static/i18n/message
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mvc:
    static-path-pattern: /
    log-resolved-exception: true
    view:
      prefix: classpath:/templates/
      suffix: .html
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: true
  devtools:
    add-properties: false
  banner:
    location: classpath:banner.txt
# Override by WebMvcConfig.class
#  web:
#    resources:
#      static-locations: classpath:/static/
storage:
  storage-type: cloudinary
  temp: ${TEMP_DIR:}
  cloudinary:
    url: ${CLOUDINARY_URL:}
  firebase:
    database-url: ${FIREBASE_DATABASE_URL:}
    storage-bucket: ${FIREBASE_STORAGE_BUCKET:}
    credentials: ${FIREBASE_CREDENTIALS:}
  local:
    upload-dir: ${UPLOAD_DIR:}
webservices:
  url:
    notification: https://delta-notification-service.herokuapp.com/delta-notification/webservice/notification.wsdl
security:
  oath2:
    resource-id: user
custom:
  http-port: 8081
  https-port: 8082
  security-policy: CONFIDENTAL
  connector-scheme: http
eureka:
  instance:
    hostname: lambda-auth-service.herokuapp.com
    secure-port-enabled: true
    non-secure-port-enabled: false
  #    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: https://chi-discovery-service.herokuapp.com/eureka
